### ISSUE TITLE
FGBio GroupReadsByUmi errors due to missing MC tags in WT and Mut BAMs

### ISSUE THREAD

**Issue by jnktsj** [ht50/FLT3_ITD_ext#1]
Hi Harrison, I have been running your perl script with FGBio 1.0.0, and the tool generated errors due to missing `MC` tags in wt and mut BAMs.  I made a fix for this based on your latest version - v1.1.  Would it be fine to make a pull request? (currently I don't have permission to make a pull request in this repo)

The fixed version runs Picard's `SortSam` to sort reads by read names instead of `samtools sort` because the Picard query sorting method is equivalent to the one that FGBio expects.  Then the sorted BAM will be piped into FGBio's SetMateInformation to add `MC` tags for the mates of the reads.

```perl
  if( system( sprintf( "%s view -bT %s %s_wt.sam | " .
                       "%s -jar %s SortSam I=/dev/stdin SO=queryname O=/dev/stdout | " .
                       "%s -jar %s SetMateInformation -i /dev/stdin -o %s_wt.bam",
        $samcmd, $reffasta, $fbase, $javacmd, $picardjar, $javacmd, $fgbiojar, $fbase ) ) ) {
    die "Failed to convert wt sam to bam. Exiting...\n";
  }
```

**Comment by ht50** [comment]
Thanks @jnktsj, just added you as a collaborator.  The fix sounds great.

**Comment by ht50** [comment]
Closing the issue, thanks again to jnktstj
